# A Travis CI configuration file.

sudo: required

language: scala
scala:
   - 2.11.6

services:
  - docker

env:
  global:
    - TERM=dumb

notifications:
  email: false

install: true

before_install:
  - openssl aes-256-cbc -K $encrypted_7d0ab4d9c9a9_key -iv $encrypted_7d0ab4d9c9a9_iv -in credentials.json.enc -out credentials.json -d
  - git clone https://github.com/openwhisk/openwhisk.git
  - cd openwhisk
  - ./tools/travis/setup.sh

script:
- ../tools/travis/build.sh
